name: Update Merged PRs

on:
  schedule:
    - cron: "0 */6 * * *"  # har 6 ghante
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch merged PRs
        run: |
          curl -s "https://api.github.com/search/issues?q=is:pr+is:merged+author:0xShubhamSolanki&sort=updated&order=desc&per_page=5" \
          | jq -r '.items[] | "- 🔀 [\(.title)](\(.html_url))"' > prs.txt

      - name: Inject into README
        run: |
          awk '/<!--START_SECTION:merged_prs-->/{print;system("cat prs.txt");next}1' README.md > temp && mv temp README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated merged PRs" || echo "No changes"
          git push
